### ISSUE TITLE
-ValueError: year 30828 is out of range

### ISSUE THREAD

**Issue by michelandre** [brandond/requests-negotiate-sspi#10]
I have an issue using this library in python 3.6.1 ->
3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]

I get ValueError: year 30828 is out of range

C:\dev\Anaconda3\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py in _response_hook(self, r, **kwargs)
    179             for scheme in ('Negotiate', 'NTLM'):
    180                 if scheme.lower() in r.headers.get('WWW-Authenticate', '').lower():
--> 181                     return self._retry_using_http_Negotiate_auth(r, scheme, kwargs)
    182 
    183 

C:\dev\Anaconda3\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py in _retry_using_http_Negotiate_auth(self, response, scheme, args)
     65         # Set up SSPI connection structure
     66         pkg_info = win32security.QuerySecurityPackageInfo(scheme)
---> 67         clientauth = sspi.ClientAuth(scheme, targetspn=targetspn, auth_info=self._auth_info)
     68         sec_buffer = win32security.PySecBufferDescType()
     69 

C:\dev\Anaconda3\lib\site-packages\win32\lib\sspi.py in __init__(self, pkg_name, client_name, auth_info, targetspn, scflags, datarep)
    109                 client_name, self.pkg_info['Name'],
    110                 sspicon.SECPKG_CRED_OUTBOUND,
--> 111                 None, auth_info)
    112         _BaseAuth.__init__(self)
    113 

ValueError: year 30828 is out of range

Dont know if its issue with sspi package or integration, seems to have been some breaking changes
https://sourceforge.net/p/pywin32/bugs/748/

**Comment by brandond** [comment]
This is an upstream issue with Pywin32 and Python 3.6.1, see https://github.com/brandond/requests-negotiate-sspi/issues/7
