### ISSUE TITLE
Error: Incorrect padding

### ISSUE THREAD

**Issue by dhirschfeld** [brandond/requests-negotiate-sspi#14]
I'm trying to connect to a web service using a gMSA and am seeing the below error:
```python-traceback
C:\Miniconda3\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py in _retry_using_http_Negotiate_auth(self, response, scheme, args)
    163         # Add challenge to security buffer
    164         tokenbuf = win32security.PySecBufferType(pkg_info['MaxToken'], sspicon.SECBUFFER_TOKEN)
--> 165         tokenbuf.Buffer = base64.b64decode(challenge[0])
    166         sec_buffer.append(tokenbuf)
    167         _logger.debug('Got Challenge Token (NTLM)')

C:\Miniconda3\lib\base64.py in b64decode(s, altchars, validate)
     85     if validate and not re.match(b'^[A-Za-z0-9+/]*={0,2}$', s):
     86         raise binascii.Error('Non-base64 digit found')
---> 87     return binascii.a2b_base64(s)
     88 
     89 

Error: Incorrect padding
```

I think the web service is buggy but wanted to post this in case it is revealing a bug in `requests-negotiate-sspi`

**Comment by dhirschfeld** [comment]
In pdb:
```
ipdb>  challenge[0]
'<snip>fYsF8k0k=,Negotiate,NTLM'
```
...so I think `b64decode` is complaining about everything to the RHS of the `=`

**Comment by brandond** [comment]
I think I've seen that before - for some reason some services will continue to stuff available auth methods into the header, instead of just responding with the base64-encoded challenge.

**Comment by dhirschfeld** [comment]
Yeah, it seems dodgy. I'm continuing to investigate if there's anything that can/should be done on the `requests-negotiate-sspi` side but running into other problems. At present I think the fix should be on the web service end rather than here though I suppose it would be nice if `requests-negotiate-sspi` could handle broken challenges

**Comment by brandond** [comment]
Can you find any examples of how other clients handle it?

**Comment by petersecurity** [comment]
Have you found a reason for the Incorrect padding error? Many thanks!

**Comment by dhirschfeld** [comment]
I haven't as I've long since dropped using that particular web service.

In case it's important, I think it was a Windows .NET app.

I'll go ahead and close since I don't think there's anything to do here. This issue can always be reopened if others also run into the same problem
