### ISSUE TITLE
Delegation support

### ISSUE THREAD

**Issue by valorl** [brandond/requests-negotiate-sspi#17]
Does the library support delegation? It does not seem to work out-of-the-box. My use-case is that the service (receiver of the request) is impersonating the identity from the ticket on the delegation level, but in order for that to work, the received kerberos token needs to be allowed for delegation. 

As per the SSPI spec at https://msdn.microsoft.com/en-us/library/windows/desktop/aa375506(v=vs.85).aspx, I'm guessing this should correspond to the `ISC_REQ_DELEGATE` flag being present.

I know that e.g. for browsers such as chrome, the domain that is trusted for delegation needs to be added in order for delegation to work.

Is there any way to make delegation work, or is it not implemented?

**Comment by brandond** [comment]
Sorry, the commit auto-closed the issue. Can you test and see if d42ae05 does what you want?

**Comment by valorl** [comment]
@brandond yep, that fixes it, thanks
