### ISSUE TITLE
Check response object attribute 'peercert' and really trim final token

### ISSUE THREAD

**Issue by aprco** [brandond/requests-negotiate-sspi#2]
For usage r = requests.get('http://host/site/default.aspx', auth=HttpNegotiateAuth()) need:

1) In line 70 add please check for object attribute 'peercert'
if hasattr(response,'peercert') and response.peercert is not None: #if response.peercert is not None:
2) In line 124 add statement '='
final=final.replace(_package, '', 1).lstrip() #final.replace(_package, '', 1).lstrip()

P.S. Thanks for your module

**Comment by brandond** [comment]
Fixed in 4b931a5 / release 0.2.2 - thanks for the report!
