### ISSUE TITLE
Setup fails because of LICENSE file extension

### ISSUE THREAD

**Issue by AndrewKo112** [brandond/requests-negotiate-sspi#8]
setup.py is looking for file "LICENSE" but it was renamed to "LICENSE.txt"

![capture](https://user-images.githubusercontent.com/8232026/27072611-9908db0c-5029-11e7-965e-dd4e239d135c.PNG)

**Comment by brandond** [comment]
Fixed, thanks. Was hoping github would pick up the license under a different name, but it appears they don't detect the short version of the Apache license regardless of what it's called.
